### AI/ML Session 1 - 26th August 2024 (further practice notebook)
### By - Heta Rahul Patel

---

## Numpy Comprehensive Function Examples

### This notebook contains examples of:

- Array Creation: Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), np.random().
- Array Properties: Checking array shape, size, and data types.
- Array Indexing and Slicing: Accessing array elements and sub-arrays.
- Reshaping Arrays: Reshaping and flattening arrays.
- Element-wise Operations: Applying mathematical operations element-wise.
- Broadcasting: Demonstrating broadcasting of smaller arrays.
- Mathematical Functions: Sum, mean, standard deviation, min/max, and more.
- Matrix Operations: Dot product, transpose, and matrix inverse.
- Random Functions: Creating arrays of random values and random integers.
- Sorting and Searching: Sorting arrays and searching for values.
- Linear Algebra: Solving linear equations.
- Saving and Loading Data: Saving and loading numpy arrays.

---

In [70]:
#import
import numpy as np

In [71]:
# 1. Array Creation
# Create a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr_1d)

1D Array:
 [1 2 3 4 5]


In [72]:
# Create a 2D array (matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr_2d)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [73]:
# Create an array of zeros
arr_zeros = np.zeros((2, 3))
print("\nArray of Zeros:\n", arr_zeros)


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [74]:
# Create an array of ones
arr_ones = np.ones((3, 3))
print("\nArray of Ones:\n", arr_ones)


Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [75]:
# Create an array with a range of values
arr_range = np.arange(0, 10, 2)
print("\nArray with Range (0 to 10, step 2):\n", arr_range)


Array with Range (0 to 10, step 2):
 [0 2 4 6 8]


In [76]:
# Create an array of random values between 0 and 1
arr_random = np.random.random((3, 3))
print("\nRandom Array (3x3):\n", arr_random)


Random Array (3x3):
 [[0.55131655 0.15153227 0.58198804]
 [0.67725355 0.99269248 0.10279785]
 [0.59294283 0.8367847  0.78595879]]


In [77]:
# 2. Array Properties
# Shape of the array
print("\nShape of arr_2d:", arr_2d.shape)


Shape of arr_2d: (2, 3)


In [78]:
# Size of the array (number of elements)
print("Size of arr_2d:", arr_2d.size)

Size of arr_2d: 6


In [79]:
# Data type of the array
print("Data type of arr_2d:", arr_2d.dtype)

Data type of arr_2d: int64


In [80]:
# 3. Array Indexing and Slicing
# Indexing in 1D array
print("\nElement at index 2 of arr_1d:", arr_1d[2])


Element at index 2 of arr_1d: 3


In [81]:
# Indexing in 2D array
print("Element at row 1, column 2 of arr_2d:", arr_2d[1, 2])

Element at row 1, column 2 of arr_2d: 6


In [82]:
# Slicing 1D array
print("\nSlicing arr_1d (from index 1 to 3):\n", arr_1d[1:4])


Slicing arr_1d (from index 1 to 3):
 [2 3 4]


In [83]:
# Slicing 2D array
print("Slicing arr_2d (first two rows and first two columns):\n", arr_2d[:2, :2])

Slicing arr_2d (first two rows and first two columns):
 [[1 2]
 [4 5]]


In [84]:
# 4. Reshaping Arrays
# Reshape a 1D array to 2D array
arr_reshaped = np.reshape(arr_1d, (5, 1))
print("\nReshaped 1D Array to 2D (5x1):\n", arr_reshaped)



Reshaped 1D Array to 2D (5x1):
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [85]:
# Flatten a 2D array to 1D array
arr_flattened = arr_2d.flatten()
print("\nFlattened 2D Array to 1D:\n", arr_flattened)


Flattened 2D Array to 1D:
 [1 2 3 4 5 6]


In [86]:
# 5. Element-wise Operations
# Add scalar to an array
arr_add = arr_1d + 5
print("\nAdd 5 to each element of arr_1d:\n", arr_add)


Add 5 to each element of arr_1d:
 [ 6  7  8  9 10]


In [87]:
# Multiply scalar with array
arr_multiply = arr_1d * 2
print("Multiply arr_1d by 2:\n", arr_multiply)

Multiply arr_1d by 2:
 [ 2  4  6  8 10]


In [88]:
# Element-wise addition of two arrays
arr_sum = arr_1d + np.array([5, 4, 3, 2, 1])
print("\nElement-wise addition of two arrays:\n", arr_sum)


Element-wise addition of two arrays:
 [6 6 6 6 6]


In [89]:
# Element-wise square root
arr_sqrt = np.sqrt(arr_1d)
print("Element-wise square root of arr_1d:\n", arr_sqrt)

Element-wise square root of arr_1d:
 [1.         1.41421356 1.73205081 2.         2.23606798]


In [90]:
# 6. Broadcasting
# Broadcasting example: adding a scalar to a 2D array
arr_broadcast = arr_2d + 10
print("\nBroadcasting Example (adding 10 to arr_2d):\n", arr_broadcast)


Broadcasting Example (adding 10 to arr_2d):
 [[11 12 13]
 [14 15 16]]


In [91]:
# Broadcasting with different shapes
arr_broadcast_diff = arr_2d + np.array([1, 2, 3])
print("\nBroadcasting Example with different shapes:\n", arr_broadcast_diff)


Broadcasting Example with different shapes:
 [[2 4 6]
 [5 7 9]]


In [92]:
# 7. Mathematical Functions
# Sum of all elements
sum_all = np.sum(arr_2d)
print("\nSum of all elements in arr_2d:", sum_all)


Sum of all elements in arr_2d: 21


In [93]:
# Sum along a specific axis
sum_axis_0 = np.sum(arr_2d, axis=0)  # Column-wise sum
print("Sum along axis 0 (column-wise sum):\n", sum_axis_0)

Sum along axis 0 (column-wise sum):
 [5 7 9]


In [94]:
sum_axis_1 = np.sum(arr_2d, axis=1)  # Row-wise sum
print("Sum along axis 1 (row-wise sum):\n", sum_axis_1)

Sum along axis 1 (row-wise sum):
 [ 6 15]


In [95]:
# Mean of the array
mean_arr = np.mean(arr_2d)
print("\nMean of arr_2d:", mean_arr)


Mean of arr_2d: 3.5


In [96]:
# Standard deviation
std_arr = np.std(arr_2d)
print("Standard deviation of arr_2d:", std_arr)

Standard deviation of arr_2d: 1.707825127659933


In [97]:
# Maximum and minimum values
max_value = np.max(arr_2d)
min_value = np.min(arr_2d)
print("\nMax value in arr_2d:", max_value)
print("Min value in arr_2d:", min_value)


Max value in arr_2d: 6
Min value in arr_2d: 1


In [98]:
# 8. Matrix Operations
# Dot product of two matrices
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr_a, arr_b)
print("\nDot Product of arr_a and arr_b:\n", dot_product)


Dot Product of arr_a and arr_b:
 [[19 22]
 [43 50]]


In [99]:
# Transpose of a matrix
arr_transpose = np.transpose(arr_a)
print("Transpose of arr_a:\n", arr_transpose)

Transpose of arr_a:
 [[1 3]
 [2 4]]


In [100]:
# Inverse of a matrix (using np.linalg.inv)
arr_square = np.array([[1, 2], [3, 4]])
arr_inverse = np.linalg.inv(arr_square)
print("\nInverse of arr_square:\n", arr_inverse)


Inverse of arr_square:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [101]:
# 9. Random Functions
# Random integers within a range
arr_randint = np.random.randint(0, 10, size=(3, 3))
print("\nRandom Integer Array (3x3) between 0 and 10:\n", arr_randint)


Random Integer Array (3x3) between 0 and 10:
 [[9 1 9]
 [3 3 1]
 [6 8 4]]


In [102]:
# Random values from a normal distribution
arr_normal = np.random.randn(3, 3)
print("\nRandom Array from Normal Distribution (3x3):\n", arr_normal)


Random Array from Normal Distribution (3x3):
 [[-1.6517186  -0.6909901  -0.77311834]
 [-2.29520706 -1.08550515 -0.51239481]
 [ 0.14515677 -0.01360191 -0.93028767]]


In [103]:
# 10. Sorting and Searching
# Sorting an array
arr_unsorted = np.array([5, 2, 9, 1, 5, 6])
arr_sorted = np.sort(arr_unsorted)
print("\nSorted Array:\n", arr_sorted)


Sorted Array:
 [1 2 5 5 6 9]


In [104]:
# Find indices of the sorted array
arr_sorted_indices = np.argsort(arr_unsorted)
print("Indices of the sorted array:\n", arr_sorted_indices)

Indices of the sorted array:
 [3 1 0 4 5 2]


In [105]:
# Searching for elements
search_index = np.where(arr_1d == 3)
print("\nIndex where arr_1d == 3:", search_index)


Index where arr_1d == 3: (array([2]),)


In [106]:
# Check conditions in an array
arr_conditional = np.where(arr_1d > 3, 'Greater', 'Lesser or Equal')
print("Conditional Check in arr_1d:\n", arr_conditional)

Conditional Check in arr_1d:
 ['Lesser or Equal' 'Lesser or Equal' 'Lesser or Equal' 'Greater' 'Greater']


In [107]:
# 11. Linear Algebra
# Solving a system of linear equations
coefficients = np.array([[3, 1], [1, 2]])
constants = np.array([9, 8])
solution = np.linalg.solve(coefficients, constants)
print("\nSolution of linear equations:\n", solution)


Solution of linear equations:
 [2. 3.]


In [108]:
# 12. Saving and Loading Data
# Save array to a file
#np.save('array_file.npy', arr_1d)
print("\nArray saved to 'array_file.npy'")


Array saved to 'array_file.npy'


In [ ]:
# Load array from file
loaded_array = np.load('array_file.npy')
print("Loaded Array from file:\n", loaded_array)

In [ ]:
## end of notebook ##